// web/src/components/apis-admin/ApiTable.vue
<template>
  <bz-table
    v-loading="loading"
    :data="rows"
    row-key="id"
    empty-text="暂无数据"
    size="small"
  >
    <bz-table-column
      label="模块"
      width="120"
      show-overflow-tooltip
    >
      <template #default="scope">
        <span class="mono">{{ scope.row.module || "-" }}</span>
      </template>
    </bz-table-column>

    <bz-table-column
      label="协议"
      width="110"
    >
      <template #default="scope">
        <bz-tag size="small">{{ scope.row.protocolLabel || scope.row.protocol }}</bz-tag>
      </template>
    </bz-table-column>

    <bz-table-column
      label="方法"
      width="110"
    >
      <template #default="scope">
        <bz-tag
          size="small"
          :type="methodTagType(scope.row.httpMethod)"
        >
          {{ scope.row.httpMethodLabel || scope.row.httpMethod }}
        </bz-tag>
      </template>
    </bz-table-column>

    <bz-table-column
      label="路径"
      min-width="420"
      show-overflow-tooltip
    >
      <template #default="scope">
        <span class="mono">{{ scope.row.pathPattern }}</span>
      </template>
    </bz-table-column>

    <bz-table-column
      label="处理器"
      min-width="380"
      show-overflow-tooltip
    >
      <template #default="scope">
        <span class="mono subdued">{{
          formatHandler(scope.row.handlerClass, scope.row.handlerMethod)
        }}</span>
      </template>
    </bz-table-column>

    <bz-table-column
      label="权限声明"
      width="110"
    >
      <template #default="scope">
        <bz-tag
          size="small"
          :type="scope.row.permissionDeclared ? 'success' : 'warning'"
        >
          {{ scope.row.permissionDeclared ? "已声明" : "未声明" }}
        </bz-tag>
      </template>
    </bz-table-column>

    <bz-table-column
      label="访问类型"
      width="130"
    >
      <template #default="scope">
        <bz-tag
          size="small"
          :type="accessTagType(scope.row.accessType)"
        >
          {{ scope.row.accessTypeLabel || scope.row.accessType }}
        </bz-tag>
      </template>
    </bz-table-column>

    <bz-table-column
      label="用户类型"
      min-width="140"
    >
      <template #default="scope">
        <div
          v-if="scope.row.userTypeLabels?.length"
          class="tag-stack"
        >
          <bz-tag
            v-for="label in scope.row.userTypeLabels"
            :key="label"
            size="small"
            type="info"
          >
            {{ label }}
          </bz-tag>
        </div>
        <span v-else>-</span>
      </template>
    </bz-table-column>

    <bz-table-column
      label="审计"
      width="110"
    >
      <template #default="scope">
        <bz-tooltip :content="scope.row.auditTooltip || ''">
          <bz-tag
            size="small"
            :type="scope.row.auditDeclared ? 'success' : 'info'"
          >
            {{ scope.row.auditDeclared ? "已开启" : "未开启" }}
          </bz-tag>
        </bz-tooltip>
      </template>
    </bz-table-column>

    <bz-table-column
      label="状态"
      width="100"
    >
      <template #default="scope">
        <bz-tag
          size="small"
          :type="scope.row.enabled ? 'success' : 'danger'"
        >
          {{ scope.row.enabled ? "启用" : "停用" }}
        </bz-tag>
      </template>
    </bz-table-column>

    <bz-table-column
      label="操作"
      width="88"
      fixed="right"
    >
      <template #default="scope">
        <AdminActionBar :actions="getRowActions(scope.row)" />
      </template>
    </bz-table-column>
  </bz-table>
</template>

<script setup lang="ts">
import type { AdminActionItem } from "../../types/admin-action";
import type { ApiEntry } from "../../types/api-admin";
import AdminActionBar from "../admin/AdminActionBar.vue";

const props = defineProps<{
  rows: ApiEntry[];
  loading: boolean;
  canPublish?: boolean;
  canDisable?: boolean;
}>();

const emit = defineEmits<{
  (e: "publish", api: ApiEntry): void;
  (e: "disable", api: ApiEntry): void;
}>();

function methodTagType(method?: string) {
  switch ((method || "").toUpperCase()) {
    case "POST":
      return "success";
    case "PUT":
      return "warning";
    case "DELETE":
      return "danger";
    case "PATCH":
      return "warning";
    default:
      return "info";
  }
}

function accessTagType(accessType?: string) {
  switch ((accessType || "").toUpperCase()) {
    case "AUTHORIZED":
      return "warning";
    case "AUTHENTICATED":
      return "primary";
    default:
      return "info";
  }
}

function formatHandler(handlerClass?: string, handlerMethod?: string) {
  if (handlerClass && handlerMethod) {
    return `${handlerClass}#${handlerMethod}`;
  }
  return handlerClass || handlerMethod || "-";
}

function getRowActions(row: ApiEntry): AdminActionItem[] {
  const actions: AdminActionItem[] = [];
  if (props.canPublish && !row.enabled) {
    actions.push({
      key: "enable",
      label: "启用",
      tone: "enable",
      handler: () => emitPublish(row),
    });
  }
  if (props.canDisable && row.enabled) {
    actions.push({
      key: "disable",
      label: "停用",
      tone: "disable",
      handler: () => emitDisable(row),
    });
  }
  return actions;
}

function emitPublish(row: ApiEntry) {
  emit("publish", row);
}

function emitDisable(row: ApiEntry) {
  emit("disable", row);
}
</script>

<style scoped>
.mono {
  font-family:
    ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New",
    monospace;
}

.subdued {
  color: var(--text-muted);
}

.tag-stack {
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
}
</style>

// web-admin/src/features/apis/ui/ApiTable.tsx
import type { ApiTableRow } from "@admin/features/apis/ui/types";
import type { AdminActionItem } from "@admin/shared/ui/admin/admin-action";
import { createAdminActionsColumn } from "@admin/shared/ui/admin/admin-actions-column";
import {
  BzOverflowTooltip,
  BzTable,
  type BzTableColumn,
  BzTag,
  BzTooltip,
} from "@admin/shared/ui/bz";

import styles from "./ApiTable.module.css";

export function ApiTable({
  rows,
  loading,
  canDetail,
  canMaintain,
  canPublish,
  canDisable,
  onDetail,
  onMaintain,
  onPublish,
  onDisable,
}: {
  rows: ApiTableRow[];
  loading: boolean;
  canDetail?: boolean;
  canMaintain?: boolean;
  canPublish?: boolean;
  canDisable?: boolean;
  onDetail: (api: ApiTableRow) => void;
  onMaintain: (api: ApiTableRow) => void;
  onPublish: (api: ApiTableRow) => void;
  onDisable: (api: ApiTableRow) => void;
}) {
  const baseColumns: Array<BzTableColumn<ApiTableRow>> = [
    {
      key: "module",
      title: "模块",
      width: 100,
      render: (row: ApiTableRow) => renderTextCell(row.module || "-", styles.mono),
    },
    {
      key: "protocol",
      title: "协议",
      width: 100,
      render: (row: ApiTableRow) => renderTag(row.protocolLabel || row.protocol || "-"),
    },
    {
      key: "httpMethod",
      title: "方法",
      width: 100,
      render: (row: ApiTableRow) => (
        <BzTag
          className={styles.tag}
          size="small"
          type={methodTagType(row.httpMethod)}
          title={row.httpMethodLabel || row.httpMethod || "-"}
        >
          <span className={styles.tagLabel}>{row.httpMethodLabel || row.httpMethod || "-"}</span>
        </BzTag>
      ),
    },
    {
      key: "pathPattern",
      title: "路径",
      minWidth: 420,
      render: (row: ApiTableRow) => renderTextCell(row.pathPattern, styles.mono, true),
    },
    {
      key: "handlerClass",
      title: "处理类",
      minWidth: 300,
      render: (row: ApiTableRow) =>
        renderTextCell(row.handlerClass || "-", `${styles.mono} ${styles.subdued}`, true),
    },
    {
      key: "handlerMethod",
      title: "处理方法",
      minWidth: 180,
      render: (row: ApiTableRow) =>
        renderTextCell(row.handlerMethod || "-", `${styles.mono} ${styles.subdued}`, true),
    },
    {
      key: "permissionDeclared",
      title: "权限声明",
      width: 100,
      render: (row: ApiTableRow) => (
        <BzTag
          className={styles.tag}
          size="small"
          type={row.permissionDeclared ? "success" : "warning"}
          title={row.permissionDeclared ? "已声明" : "未声明"}
        >
          <span className={styles.tagLabel}>{row.permissionDeclared ? "已声明" : "未声明"}</span>
        </BzTag>
      ),
    },
    {
      key: "accessType",
      title: "访问类型",
      width: 100,
      render: (row: ApiTableRow) => (
        <BzTag
          className={styles.tag}
          size="small"
          type={accessTagType(row.accessType)}
          title={row.accessTypeLabel || row.accessType || "-"}
        >
          <span className={styles.tagLabel}>{row.accessTypeLabel || row.accessType || "-"}</span>
        </BzTag>
      ),
    },
    {
      key: "userType",
      title: "用户类型",
      width: 100,
      render: (row: ApiTableRow) =>
        row.userTypeLabel ? (
          <BzTag
            className={styles.tag}
            size="small"
            type="info"
            title={row.userTypeLabel}
          >
            <span className={styles.tagLabel}>{row.userTypeLabel}</span>
          </BzTag>
        ) : (
          renderTextCell("-")
        ),
    },
    {
      key: "audit",
      title: "审计",
      width: 100,
      render: (row: ApiTableRow) => (
        <BzTooltip content={row.auditTooltip || ""}>
          <span>
            <BzTag
              className={styles.tag}
              size="small"
              type={row.auditDeclared ? "success" : "info"}
              title={row.auditDeclared ? "已开启" : "未开启"}
            >
              <span className={styles.tagLabel}>{row.auditDeclared ? "已开启" : "未开启"}</span>
            </BzTag>
          </span>
        </BzTooltip>
      ),
    },
    {
      key: "enabled",
      title: "状态",
      width: 100,
      render: (row: ApiTableRow) => (
        <BzTag
          className={styles.tag}
          size="small"
          type={row.enabled ? "success" : "danger"}
          title={row.enabled ? "启用" : "停用"}
        >
          <span className={styles.tagLabel}>{row.enabled ? "启用" : "停用"}</span>
        </BzTag>
      ),
    },
  ];

  const actionsColumn = createAdminActionsColumn({
    rows,
    getActions: (row) =>
      getRowActions(
        row,
        canDetail,
        canMaintain,
        canPublish,
        canDisable,
        onDetail,
        onMaintain,
        onPublish,
        onDisable,
      ),
    stickyClassName: `${styles.actionsCell} is-fixed-right`,
    stickyHeaderClassName: `${styles.actionsCell} is-fixed-right`,
  });
  if (actionsColumn) baseColumns.push(actionsColumn);

  const columns: Array<BzTableColumn<ApiTableRow>> = baseColumns.map((column) => ({
    ...column,
    className: [styles.cell, column.className].filter(Boolean).join(" "),
    headerClassName: [styles.headerCell, column.headerClassName].filter(Boolean).join(" "),
  }));

  return (
    <div className={styles.tableScope}>
      <BzTable
        data={rows}
        columns={columns}
        rowKey="id"
        loading={loading}
        emptyText="暂无数据"
        size="small"
      />
    </div>
  );
}

function renderTextCell(value: string, className?: string, withOverflowTooltip = false) {
  const content = (
    <span className={[styles.text, className].filter(Boolean).join(" ")}>{value}</span>
  );
  if (!withOverflowTooltip) {
    return content;
  }
  return <BzOverflowTooltip text={value}>{content}</BzOverflowTooltip>;
}

function renderTag(label: string, type: "info" | "warning" | "danger" | "success" = "info") {
  return (
    <BzTag
      className={styles.tag}
      size="small"
      type={type}
      title={label}
    >
      <span className={styles.tagLabel}>{label}</span>
    </BzTag>
  );
}

function methodTagType(method?: string): "info" | "success" | "warning" | "danger" {
  switch ((method || "").toUpperCase()) {
    case "POST":
      return "success";
    case "PUT":
    case "PATCH":
      return "warning";
    case "DELETE":
      return "danger";
    default:
      return "info";
  }
}

function accessTagType(accessType?: string): "info" | "success" | "warning" | "danger" {
  switch ((accessType || "").toUpperCase()) {
    case "AUTHORIZED":
      return "warning";
    case "AUTHENTICATED":
      return "success";
    default:
      return "info";
  }
}

function getRowActions(
  row: ApiTableRow,
  canDetail: boolean | undefined,
  canMaintain: boolean | undefined,
  canPublish: boolean | undefined,
  canDisable: boolean | undefined,
  onDetail: (api: ApiTableRow) => void,
  onMaintain: (api: ApiTableRow) => void,
  onPublish: (api: ApiTableRow) => void,
  onDisable: (api: ApiTableRow) => void,
): AdminActionItem[] {
  const actions: AdminActionItem[] = [];
  if (canDetail)
    actions.push({ key: "detail", label: "详情", level: "default", onClick: () => onDetail(row) });
  if (canMaintain)
    actions.push({
      key: "maintain",
      label: "维护",
      level: "primary",
      onClick: () => onMaintain(row),
    });
  if (canPublish)
    actions.push({
      key: "enable",
      label: "启用",
      level: "success",
      disabled: row.enabled,
      onClick: () => onPublish(row),
    });
  if (canDisable)
    actions.push({
      key: "disable",
      label: "停用",
      level: "warning",
      disabled: !row.enabled,
      onClick: () => onDisable(row),
    });
  return actions;
}
