// web-admin/src/components/users-admin/UserTable.tsx
import { formatDateTime } from "../../core/formatter";
import type { AdminActionItem } from "../../types/admin-action";
import type { UserEntry } from "../../types/user-admin";
import { AdminActionBar } from "../admin/AdminActionBar";
import type { BzTableColumn } from "../bz/BzTable";
import { BzTable } from "../bz/BzTable";
import { BzTag } from "../bz/BzTag";

interface UserTypeMeta {
  label: string;
  tagType?: string | null;
}

interface UserTableProps {
  rows: UserEntry[];
  loading: boolean;
  canEdit: boolean;
  canToggle: boolean;
  canReset: boolean;
  canRoles: boolean;
  canDelete: boolean;
  userTypeMetaMap?: Record<string, UserTypeMeta>;
  onEdit: (user: UserEntry) => void;
  onToggle: (user: UserEntry) => void;
  onReset: (user: UserEntry) => void;
  onRoles: (user: UserEntry) => void;
  onRemove: (user: UserEntry) => void;
}

export function UserTable({
  rows,
  loading,
  canEdit,
  canToggle,
  canReset,
  canRoles,
  canDelete,
  userTypeMetaMap = {},
  onEdit,
  onToggle,
  onReset,
  onRoles,
  onRemove,
}: UserTableProps) {
  function resolveUserTypeLabel(userType: string): string {
    return userTypeMetaMap[userType]?.label || userType;
  }
  function resolveUserTypeTagType(userType: string): "info" | "success" | "warning" | "danger" {
    const t = userTypeMetaMap[userType]?.tagType;
    if (t === "success" || t === "warning" || t === "danger" || t === "info") return t;
    return "info";
  }
  function getActions(user: UserEntry): AdminActionItem[] {
    const actions: AdminActionItem[] = [];
    if (canEdit)
      actions.push({ key: "edit", label: "编辑", tone: "edit", handler: () => onEdit(user) });
    if (canToggle)
      actions.push({
        key: "toggle",
        label: user.status === "ENABLED" ? "停用" : "启用",
        tone: user.status === "ENABLED" ? "disable" : "enable",
        handler: () => onToggle(user),
      });
    if (canReset) actions.push({ key: "reset", label: "重置密码", handler: () => onReset(user) });
    if (canRoles && user.userType !== "EXTERNAL")
      actions.push({ key: "roles", label: "角色", handler: () => onRoles(user) });
    if (canDelete)
      actions.push({ key: "delete", label: "删除", tone: "delete", handler: () => onRemove(user) });
    return actions;
  }

  const columns: Array<BzTableColumn<UserEntry>> = [
    {
      key: "username",
      title: "账号",
      minWidth: 180,
      render: (row) => <div className="name">{row.username}</div>,
    },
    { key: "nickname", title: "昵称", minWidth: 160, render: (row) => row.nickname || "-" },
    {
      key: "userType",
      title: "类型",
      width: 120,
      render: (row) => (
        <BzTag type={resolveUserTypeTagType(row.userType)}>
          {resolveUserTypeLabel(row.userType)}
        </BzTag>
      ),
    },
    {
      key: "status",
      title: "状态",
      width: 110,
      render: (row) => {
        const active = row.status === "ENABLED";
        return <BzTag type={active ? "success" : "danger"}>{active ? "启用" : "停用"}</BzTag>;
      },
    },
    { key: "createdBy", title: "创建人", width: 140, render: (row) => row.createdBy || "-" },
    {
      key: "createdAt",
      title: "创建时间",
      width: 170,
      render: (row) => formatDateTime(row.createdAt),
    },
    { key: "updatedBy", title: "更新人", width: 140, render: (row) => row.updatedBy || "-" },
    {
      key: "updatedAt",
      title: "更新时间",
      width: 170,
      render: (row) => formatDateTime(row.updatedAt),
    },
    {
      key: "actions",
      title: "操作",
      width: 180,
      render: (row) => {
        const all = getActions(row);
        return (
          <AdminActionBar actions={all.filter((a) => a.key === "edit" || a.key === "roles")} />
        );
      },
    },
  ];

  return (
    <BzTable
      data={rows}
      columns={columns}
      rowKey="id"
      loading={loading}
      emptyText="暂无数据"
      size="small"
    />
  );
}

// web-admin/src/components/users-admin/UserTable.vue
<template>
  <bz-table
    v-loading="loading"
    :data="rows"
    row-key="id"
    empty-text="暂无数据"
    size="small"
  >
    <bz-table-column
      prop="username"
      label="账号"
      min-width="180"
    >
      <template #default="scope">
        <div class="name">{{ scope.row.username }}</div>
      </template>
    </bz-table-column>
    <bz-table-column
      prop="nickname"
      label="昵称"
      min-width="160"
    >
      <template #default="scope">
        {{ scope.row.nickname || "-" }}
      </template>
    </bz-table-column>
    <bz-table-column
      label="类型"
      width="120"
    >
      <template #default="scope">
        <bz-tag :type="resolveUserTypeTagType(scope.row.userType)">
          {{ resolveUserTypeLabel(scope.row.userType) }}
        </bz-tag>
      </template>
    </bz-table-column>
    <bz-table-column
      label="状态"
      width="110"
    >
      <template #default="scope">
        <bz-tag
          :type="
            scope.row.status === 'ENABLED' || scope.row.status === 'ACTIVE' ? 'success' : 'warning'
          "
        >
          {{
            scope.row.status === "ENABLED" || scope.row.status === "ACTIVE"
              ? "启用"
              : scope.row.status === "CANCELLED"
                ? "已注销"
                : "停用"
          }}
        </bz-tag>
      </template>
    </bz-table-column>
    <bz-table-column
      prop="createdBy"
      label="创建人"
      width="140"
    >
      <template #default="scope">
        {{ scope.row.createdBy || "-" }}
      </template>
    </bz-table-column>
    <bz-table-column
      label="创建时间"
      width="170"
    >
      <template #default="scope">
        {{ formatDateTime(scope.row.createdAt) }}
      </template>
    </bz-table-column>
    <bz-table-column
      prop="updatedBy"
      label="更新人"
      width="140"
    >
      <template #default="scope">
        {{ scope.row.updatedBy || "-" }}
      </template>
    </bz-table-column>
    <bz-table-column
      label="更新时间"
      width="170"
    >
      <template #default="scope">
        {{ formatDateTime(scope.row.updatedAt) }}
      </template>
    </bz-table-column>
    <bz-table-column
      label="操作"
      width="180"
      fixed="right"
    >
      <template #default="scope">
        <AdminActionBar
          :actions="getPrimaryActions(scope.row)"
          :more-actions="getExtraActions(scope.row)"
        />
      </template>
    </bz-table-column>
  </bz-table>
</template>

<script setup lang="ts">
import AdminActionBar from "@admin/components/admin/AdminActionBar.vue";
import type { UserEntry } from "@admin/types/user-admin";
import { formatDateTime } from "@shared/utils/formatter";

interface UserTypeMeta {
  label: string;
  tagType?: string | null;
}

const props = defineProps<{
  rows: UserEntry[];
  loading: boolean;
  canEdit: boolean;
  canToggle: boolean;
  canReset: boolean;
  canRoles: boolean;
  canDelete: boolean;
  userTypeMetaMap?: Record<string, UserTypeMeta>;
}>();

const emit = defineEmits<{
  (e: "edit", user: UserEntry): void;
  (e: "toggle", user: UserEntry): void;
  (e: "reset", user: UserEntry): void;
  (e: "roles", user: UserEntry): void;
  (e: "remove", user: UserEntry): void;
}>();

interface RowAction {
  key: string;
  label: string;
  tone?: "edit" | "enable" | "disable" | "delete" | "detail" | "neutral";
  disabled?: boolean;
  handler: () => void;
}

function resolveUserTypeLabel(userType: UserEntry["userType"]): string {
  return props.userTypeMetaMap?.[userType]?.label || userType;
}

function resolveUserTypeTagType(userType: UserEntry["userType"]): string {
  return props.userTypeMetaMap?.[userType]?.tagType || "info";
}

function getRowActions(user: UserEntry): RowAction[] {
  const actions: RowAction[] = [];
  if (props.canEdit) {
    actions.push({
      key: "edit",
      label: "编辑",
      tone: "edit",
      handler: () => emit("edit", user),
    });
  }
  if (props.canToggle) {
    actions.push({
      key: "toggle",
      label: user.status === "ENABLED" ? "停用" : "启用",
      tone: user.status === "ENABLED" ? "disable" : "enable",
      handler: () => emit("toggle", user),
    });
  }
  if (props.canReset) {
    actions.push({
      key: "reset",
      label: "重置密码",
      handler: () => emit("reset", user),
    });
  }
  if (props.canRoles && user.userType !== "EXTERNAL") {
    actions.push({
      key: "roles",
      label: "角色",
      handler: () => emit("roles", user),
    });
  }
  if (props.canDelete) {
    actions.push({
      key: "delete",
      label: "删除",
      tone: "delete",
      handler: () => emit("remove", user),
    });
  }
  return actions;
}

function getPrimaryActions(user: UserEntry): RowAction[] {
  const actions = getRowActions(user);
  return actions.filter((action) => action.key === "edit" || action.key === "roles");
}

function getExtraActions(user: UserEntry): RowAction[] {
  const actions = getRowActions(user);
  return actions.filter((action) => action.key !== "edit" && action.key !== "roles");
}
</script>

<style scoped>
.name {
  font-weight: 800;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
</style>
