// web-admin/src/components/users-admin/UserFormDialog.vue
<template>
  <bz-dialog
    :model-value="true"
    :title="mode === 'create' ? '新增用户' : '编辑用户'"
    width="520px"
    @close="$emit('close')"
  >
    <bz-form label-position="top">
      <bz-form-item label="用户名 *">
        <bz-input
          v-model="m.username"
          :disabled="mode === 'edit'"
          placeholder="请输入用户名"
        />
      </bz-form-item>
      <bz-form-item label="昵称 *">
        <bz-input
          v-model="m.nickname"
          placeholder="请输入昵称"
        />
      </bz-form-item>
      <bz-form-item
        v-if="mode === 'create'"
        label="密码 *"
      >
        <bz-input
          v-model="m.password"
          type="password"
          placeholder="请输入初始密码"
          show-password
        />
      </bz-form-item>
      <bz-form-item
        v-if="mode === 'edit'"
        label="状态 *"
      >
        <bz-select v-model="m.status">
          <bz-option
            label="启用"
            value="ENABLED"
          />
          <bz-option
            label="停用"
            value="DISABLED"
          />
        </bz-select>
      </bz-form-item>
    </bz-form>
    <bz-alert
      v-if="err"
      :title="err"
      type="error"
      show-icon
      class="form-error"
    />
    <template #footer>
      <bz-button @click="$emit('close')">取消</bz-button>
      <bz-button
        type="primary"
        @click="submit"
      >
        {{ mode === "create" ? "创建" : "保存" }}
      </bz-button>
    </template>
  </bz-dialog>
</template>

<script setup lang="ts">
import type { UserEntry, UserStatus } from "@admin/types/user-admin";
import { reactive, ref, watch } from "vue";

const props = defineProps<{
  mode: "create" | "edit";
  model: UserEntry | null;
}>();

const emit = defineEmits<{
  (e: "close"): void;
  (
    e: "submit",
    payload: { username: string; nickname: string; password?: string; status: UserStatus },
  ): void;
}>();

const m = reactive({
  username: "",
  nickname: "",
  password: "",
  status: "ENABLED" as UserStatus,
});

const err = ref("");

watch(
  () => props.model,
  (value) => {
    if (!value) return;
    m.username = value.username;
    m.nickname = value.nickname || "";
    m.password = "";
    m.status = value.status;
  },
  { immediate: true },
);

function validate(): string {
  if (!m.username.trim()) return "用户名不能为空";
  if (!m.nickname.trim()) return "昵称不能为空";
  if (props.mode === "create" && !m.password.trim()) return "密码不能为空";
  return "";
}

function submit() {
  err.value = "";
  const validationError = validate();
  if (validationError) {
    err.value = validationError;
    return;
  }
  const payload: { username: string; nickname: string; password?: string; status: UserStatus } = {
    username: m.username.trim(),
    nickname: m.nickname.trim(),
    status: m.status,
  };
  if (props.mode === "create") {
    payload.password = m.password.trim();
  }
  emit("submit", payload);
}
</script>

<style scoped>
.form-error {
  margin-top: 4px;
}
</style>

// web-admin/src/components/users-admin/UserFormDialog.tsx
import { useEffect, useState } from "react";

import type { UserStatus } from "../../types/user-admin";
import { BzAlert } from "../bz/BzAlert";
import { BzButton } from "../bz/BzButton";
import { BzDialog } from "../bz/BzDialog";
import { BzForm } from "../bz/BzForm";
import { BzFormItem } from "../bz/BzFormItem";
import { BzInput } from "../bz/BzInput";
import { BzOption } from "../bz/BzOption";
import { BzSelect } from "../bz/BzSelect";

interface UserFormDialogProps {
  mode: "create" | "edit";
  model: { id: string; username: string; nickname: string; userType: string; status: UserStatus } | null;
  onClose: () => void;
  onSubmit: (payload: { username: string; nickname: string; password?: string; status: UserStatus }) => void;
}

export function UserFormDialog({ mode, model, onClose, onSubmit }: UserFormDialogProps) {
  const [username, setUsername] = useState("");
  const [nickname, setNickname] = useState("");
  const [password, setPassword] = useState("");
  const [status, setStatus] = useState<UserStatus>("ENABLED");
  const [err, setErr] = useState("");

  useEffect(() => {
    if (model) {
      setUsername(model.username);
      setNickname(model.nickname || "");
      setPassword("");
      setStatus(model.status);
    }
  }, [model]);

  function validate(): string {
    if (!username.trim()) return "用户名不能为空";
    if (!nickname.trim()) return "昵称不能为空";
    if (mode === "create" && !password.trim()) return "密码不能为空";
    return "";
  }

  function handleSubmit() {
    setErr("");
    const e = validate();
    if (e) { setErr(e); return; }
    const payload: { username: string; nickname: string; password?: string; status: UserStatus } = {
      username: username.trim(), nickname: nickname.trim(), status,
    };
    if (mode === "create") payload.password = password.trim();
    onSubmit(payload);
  }

  return (
    <BzDialog modelValue={true} title={mode === "create" ? "新增用户" : "编辑用户"} width="520px" onClose={onClose}
      footer={<div style={{ display: "flex", gap: 8 }}><BzButton onClick={onClose}>取消</BzButton><BzButton buttonType="primary" onClick={handleSubmit}>{mode === "create" ? "创建" : "保存"}</BzButton></div>}>
      <BzForm>
        <BzFormItem label="用户名 *">
          <BzInput modelValue={username} disabled={mode === "edit"} placeholder="请输入用户名" onValueChange={setUsername} />
        </BzFormItem>
        <BzFormItem label="昵称 *">
          <BzInput modelValue={nickname} placeholder="请输入昵称" onValueChange={setNickname} />
        </BzFormItem>
        {mode === "create" ? (
          <BzFormItem label="密码 *">
            <BzInput modelValue={password} type="password" placeholder="请输入初始密码" onValueChange={setPassword} />
          </BzFormItem>
        ) : null}
        {mode === "edit" ? (
          <BzFormItem label="状态 *">
            <BzSelect modelValue={status} onValueChange={(v) => setStatus((v as UserStatus) || "ENABLED")}>
              <BzOption label="启用" value="ENABLED" />
              <BzOption label="停用" value="DISABLED" />
            </BzSelect>
          </BzFormItem>
        ) : null}
      </BzForm>
      {err ? <BzAlert title={err} type="error" showIcon className="form-error" /> : null}
    </BzDialog>
  );
}
