// web-admin/src/components/apis-admin/ApiTable.vue
<template>
  <bz-table
    v-loading="loading"
    :data="rows"
    row-key="id"
    empty-text="暂无数据"
    size="small"
  >
    <bz-table-column
      label="模块"
      width="120"
      show-overflow-tooltip
    >
      <template #default="scope">
        <span class="mono">{{ scope.row.module || "-" }}</span>
      </template>
    </bz-table-column>

    <bz-table-column
      label="协议"
      width="110"
    >
      <template #default="scope">
        <bz-tag size="small">{{ scope.row.protocolLabel || scope.row.protocol }}</bz-tag>
      </template>
    </bz-table-column>

    <bz-table-column
      label="方法"
      width="110"
    >
      <template #default="scope">
        <bz-tag
          size="small"
          :type="methodTagType(scope.row.httpMethod)"
        >
          {{ scope.row.httpMethodLabel || scope.row.httpMethod }}
        </bz-tag>
      </template>
    </bz-table-column>

    <bz-table-column
      label="路径"
      min-width="420"
      show-overflow-tooltip
    >
      <template #default="scope">
        <span class="mono">{{ scope.row.pathPattern }}</span>
      </template>
    </bz-table-column>

    <bz-table-column
      label="处理器"
      min-width="380"
      show-overflow-tooltip
    >
      <template #default="scope">
        <span class="mono subdued">{{
          formatHandler(scope.row.handlerClass, scope.row.handlerMethod)
        }}</span>
      </template>
    </bz-table-column>

    <bz-table-column
      label="权限声明"
      width="110"
    >
      <template #default="scope">
        <bz-tag
          size="small"
          :type="scope.row.permissionDeclared ? 'success' : 'warning'"
        >
          {{ scope.row.permissionDeclared ? "已声明" : "未声明" }}
        </bz-tag>
      </template>
    </bz-table-column>

    <bz-table-column
      label="访问类型"
      width="130"
    >
      <template #default="scope">
        <bz-tag
          size="small"
          :type="accessTagType(scope.row.accessType)"
        >
          {{ scope.row.accessTypeLabel || scope.row.accessType }}
        </bz-tag>
      </template>
    </bz-table-column>

    <bz-table-column
      label="用户类型"
      min-width="140"
    >
      <template #default="scope">
        <div
          v-if="scope.row.userTypeLabels?.length"
          class="tag-stack"
        >
          <bz-tag
            v-for="label in scope.row.userTypeLabels"
            :key="label"
            size="small"
            type="info"
          >
            {{ label }}
          </bz-tag>
        </div>
        <span v-else>-</span>
      </template>
    </bz-table-column>

    <bz-table-column
      label="审计"
      width="110"
    >
      <template #default="scope">
        <bz-tooltip :content="scope.row.auditTooltip || ''">
          <bz-tag
            size="small"
            :type="scope.row.auditDeclared ? 'success' : 'info'"
          >
            {{ scope.row.auditDeclared ? "已开启" : "未开启" }}
          </bz-tag>
        </bz-tooltip>
      </template>
    </bz-table-column>

    <bz-table-column
      label="状态"
      width="100"
    >
      <template #default="scope">
        <bz-tag
          size="small"
          :type="scope.row.enabled ? 'success' : 'danger'"
        >
          {{ scope.row.enabled ? "启用" : "停用" }}
        </bz-tag>
      </template>
    </bz-table-column>

    <bz-table-column
      label="操作"
      width="88"
      fixed="right"
    >
      <template #default="scope">
        <AdminActionBar :actions="getRowActions(scope.row)" />
      </template>
    </bz-table-column>
  </bz-table>
</template>

<script setup lang="ts">
import AdminActionBar from "@admin/components/admin/AdminActionBar.vue";
import type { AdminActionItem } from "@admin/types/admin-action";
import type { ApiEntry } from "@admin/types/api-admin";

const props = defineProps<{
  rows: ApiEntry[];
  loading: boolean;
  canPublish?: boolean;
  canDisable?: boolean;
}>();

const emit = defineEmits<{
  (e: "publish", api: ApiEntry): void;
  (e: "disable", api: ApiEntry): void;
}>();

function methodTagType(method?: string) {
  switch ((method || "").toUpperCase()) {
    case "POST":
      return "success";
    case "PUT":
      return "warning";
    case "DELETE":
      return "danger";
    case "PATCH":
      return "warning";
    default:
      return "info";
  }
}

function accessTagType(accessType?: string) {
  switch ((accessType || "").toUpperCase()) {
    case "AUTHORIZED":
      return "warning";
    case "AUTHENTICATED":
      return "primary";
    default:
      return "info";
  }
}

function formatHandler(handlerClass?: string, handlerMethod?: string) {
  if (handlerClass && handlerMethod) {
    return `${handlerClass}#${handlerMethod}`;
  }
  return handlerClass || handlerMethod || "-";
}

function getRowActions(row: ApiEntry): AdminActionItem[] {
  const actions: AdminActionItem[] = [];
  if (props.canPublish && !row.enabled) {
    actions.push({
      key: "enable",
      label: "启用",
      tone: "enable",
      handler: () => emitPublish(row),
    });
  }
  if (props.canDisable && row.enabled) {
    actions.push({
      key: "disable",
      label: "停用",
      tone: "disable",
      handler: () => emitDisable(row),
    });
  }
  return actions;
}

function emitPublish(row: ApiEntry) {
  emit("publish", row);
}

function emitDisable(row: ApiEntry) {
  emit("disable", row);
}
</script>

<style scoped>
.mono {
  font-family:
    ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New",
    monospace;
}

.subdued {
  color: var(--text-muted);
}

.tag-stack {
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
}
</style>

// web-admin/src/components/apis-admin/ApiTable.tsx
import { AdminActionBar } from "@admin/components/admin/AdminActionBar";
import { BzTable, type BzTableColumn, BzTag, BzTooltip } from "@admin/components/bz";
import type { AdminActionItem } from "@admin/types/admin-action";
import type { ApiEntry } from "@admin/types/api-admin";

export function ApiTable({
  rows,
  loading,
  canPublish,
  canDisable,
  onPublish,
  onDisable,
}: {
  rows: ApiEntry[];
  loading: boolean;
  canPublish?: boolean;
  canDisable?: boolean;
  onPublish: (api: ApiEntry) => void;
  onDisable: (api: ApiEntry) => void;
}) {
  const columns: Array<BzTableColumn<ApiEntry>> = [
    {
      key: "module",
      title: "模块",
      width: 120,
      render: (row) => <span className="mono">{row.module || "-"}</span>,
    },
    {
      key: "protocol",
      title: "协议",
      width: 110,
      render: (row) => <BzTag size="small">{row.protocolLabel || row.protocol}</BzTag>,
    },
    {
      key: "httpMethod",
      title: "方法",
      width: 110,
      render: (row) => (
        <BzTag
          size="small"
          type={methodTagType(row.httpMethod)}
        >
          {row.httpMethodLabel || row.httpMethod}
        </BzTag>
      ),
    },
    {
      key: "pathPattern",
      title: "路径",
      minWidth: 420,
      render: (row) => <span className="mono">{row.pathPattern}</span>,
    },
    {
      key: "handlerClass",
      title: "处理类",
      minWidth: 300,
      render: (row) => <span className="mono subdued">{row.handlerClass || "-"}</span>,
    },
    {
      key: "handlerMethod",
      title: "处理方法",
      minWidth: 180,
      render: (row) => <span className="mono subdued">{row.handlerMethod || "-"}</span>,
    },
    {
      key: "permissionDeclared",
      title: "权限声明",
      width: 110,
      render: (row) => (
        <BzTag
          size="small"
          type={row.permissionDeclared ? "success" : "warning"}
        >
          {row.permissionDeclared ? "已声明" : "未声明"}
        </BzTag>
      ),
    },
    {
      key: "accessType",
      title: "访问类型",
      width: 130,
      render: (row) => (
        <BzTag
          size="small"
          type={accessTagType(row.accessType)}
        >
          {row.accessTypeLabel || row.accessType}
        </BzTag>
      ),
    },
    {
      key: "userTypes",
      title: "用户类型",
      minWidth: 140,
      render: (row) =>
        row.userTypeLabels?.length ? (
          <div className="tag-stack">
            {row.userTypeLabels.map((label) => (
              <BzTag
                key={label}
                size="small"
                type="info"
              >
                {label}
              </BzTag>
            ))}
          </div>
        ) : (
          <span>-</span>
        ),
    },
    {
      key: "audit",
      title: "审计",
      width: 110,
      render: (row) => (
        <BzTooltip content={row.auditTooltip || ""}>
          <span>
            <BzTag
              size="small"
              type={row.auditDeclared ? "success" : "info"}
            >
              {row.auditDeclared ? "已开启" : "未开启"}
            </BzTag>
          </span>
        </BzTooltip>
      ),
    },
    {
      key: "enabled",
      title: "状态",
      width: 100,
      render: (row) => (
        <BzTag
          size="small"
          type={row.enabled ? "success" : "danger"}
        >
          {row.enabled ? "启用" : "停用"}
        </BzTag>
      ),
    },
    {
      key: "actions",
      title: "操作",
      width: 88,
      render: (row) => (
        <AdminActionBar
          actions={getRowActions(row, canPublish, canDisable, onPublish, onDisable)}
        />
      ),
    },
  ];

  return (
    <BzTable
      data={rows}
      columns={columns}
      rowKey="id"
      loading={loading}
      emptyText="暂无数据"
      size="small"
    />
  );
}

function methodTagType(method?: string): "info" | "success" | "warning" | "danger" {
  switch ((method || "").toUpperCase()) {
    case "POST":
      return "success";
    case "PUT":
    case "PATCH":
      return "warning";
    case "DELETE":
      return "danger";
    default:
      return "info";
  }
}

function accessTagType(accessType?: string): "info" | "success" | "warning" | "danger" {
  switch ((accessType || "").toUpperCase()) {
    case "AUTHORIZED":
      return "warning";
    case "AUTHENTICATED":
      return "success";
    default:
      return "info";
  }
}

function getRowActions(
  row: ApiEntry,
  canPublish: boolean | undefined,
  canDisable: boolean | undefined,
  onPublish: (api: ApiEntry) => void,
  onDisable: (api: ApiEntry) => void,
): AdminActionItem[] {
  const actions: AdminActionItem[] = [];
  if (canPublish && !row.enabled)
    actions.push({ key: "enable", label: "启用", tone: "enable", handler: () => onPublish(row) });
  if (canDisable && row.enabled)
    actions.push({ key: "disable", label: "停用", tone: "disable", handler: () => onDisable(row) });
  return actions;
}
